name: Lint and Test
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Testing
    steps:
    - uses: actions/checkout@v2
        
    - name: Install modules
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Run tests
      env:
        SESSDATA: ${{ secrets.SESSDATA }}
        bili_jct: ${{ secrets.BILI_JCT }}
      run: npm test
      
